language: node_js
node_js:
  - "0.10"
install: npm install
script: npm run test-ci
branches:
  only:
    - master
env:
  global:
    - SAUCE_USERNAME=os-algolia-faux-jax
    - SAUCE_ACCESS_KEY=60276788-fd33-42b9-bfbe-9180e63c7c64
